### ISSUE TITLE
Module connection with the MagicMirror failure

### ISSUE THREAD

**Issue by ryryii** [nischi/MMM-Face-Reco-DNN#1]
As far as I can tell the facial recognition is working correctly, it was able to recognize specific faces when facerecognition.py is ran. After adding the module to the Mirror config file the mirror would not load, Electron launches but it appears the module is causing the mirror to crash. (exact same configuration as in the readme) There are no errors, I just get the gray screen with the cursor. 

I have tested other modules and checked for js validation errors and please note the MM-Face-Reco-DNN module is up to date as of this posting. 

If you have any idea what could be causing this please let me know.

**Comment by nischi** [comment]
Hmm without any error message is difficult to say whats wrong. If you say facerecognition.py run successfull you should have installed all dependencies correctly. 

Have you tried to run MagicMirror in dev mode? `npm run start dev`?

Maybe you will get more information in the Browser Console. How do you start your MagicMirror?
