### ISSUE TITLE
Confused on what to do.

### ISSUE THREAD

**Issue by aliencord** [nischi/MMM-Face-Reco-DNN#101]
I am stumped on how to setup this module if you could please help me out i would love to use this module.

**Comment by nischi** [comment]
The readme should help you to setup the module. If not you need to tell us where you stuck or where you are exactly confused.

**Comment by aliencord** [comment]
I am stumped on setting up the face data set, container, and embeddings.

**Comment by nischi** [comment]
Sorry i can't help you with this description.
