### ISSUE TITLE
Problems with Notifications

### ISSUE THREAD

**Issue by jokerxshot** [nischi/MMM-Face-Reco-DNN#103]
I've noticed that with the welcomemessage enabled it does create a notification using the alerts module but when it does it only says, "title" and "knownlogin" under it. Is there a way to change it to the name of the class it's logging into? Shouldn't it just get the name from the name of the class?

**Comment by nischi** [comment]
Then you have a language set, which is not in the application. Which language did you set?

**Comment by nischi** [comment]
We do have this languages. <img width="134" alt="Bildschirmfoto 2021-07-25 um 15 39 00" src="https://user-images.githubusercontent.com/2036054/126901122-8f19ec66-cef7-40cc-91aa-ccf9060cf2f6.png">

**Comment by jokerxshot** [comment]
That is my bad I for some reason had the translations folder deleted completely as well in the js file. It works fine now thank you!
