### ISSUE TITLE
Confused on a few steps :)

### ISSUE THREAD

**Issue by aarishrajwani** [nischi/MMM-Face-Reco-DNN#106]
Hey, I am trying to get this module running but I got stuck in a few spots.

First, I created a folder in home/pi/MagicMirror/modules/MMM-Face-Reco-DNN called "dataset". In /home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/**dataset** I have a folder with my name. In that folder I have 11 images all numbered. Is that correct. I have added nothing else besides that, am i missing anything or is that correct?

Second, I am completely lost on what to do with the encode.py file. Am I supposed to modify the values in that files and if so which ones? Sorry if these are basic questions I'm relatively new to this.

**Comment by nischi** [comment]
@Aarish12 

Hi

The dataset seems to be correct as you wrote. 

To the second question, no you do not need to change anything on the encode.py file. you need to run it to generate the `encodings.pickle` file. Which is used to identify your face. 

You need to run the script with python.
