### ISSUE TITLE
libcamera support

### ISSUE THREAD

**Issue by goldyfruit** [nischi/MMM-Face-Reco-DNN#114]
Hi,

Is there any plan to make this module compatible with the new camera interface of Raspberry Pi OS 64-bit?
Raspberry Pi OS 64-bit doesn't work anymore with the Python `picamera` library.

Libcamera is the new "default" interface to interact with camera, more information available here: https://www.raspberrypi.com/documentation/accessories/camera.html#libcamera-and-libcamera-apps

Thanks :)

**Comment by nischi** [comment]
Hi

Would be nice, but i do not have any time at the moment. so i would be happy if we have a PR for that.

Thanks.

**Comment by goldyfruit** [comment]
Seems that `picamera2` has been released; https://www.raspberrypi.com/news/picamera2-beta-release/

**Comment by HW594** [comment]
Hi.

Do you have a plan to use this module with the actualy PiOS with libcamera library or with the picamera2 library or does anyone have another solution for the problem?

Thanks.

**Comment by goldyfruit** [comment]
@nischi is there any commit related to this change?

**Comment by nischi** [comment]
nope 🙈

**Comment by goldyfruit** [comment]
But after checking in the code repo, since `tools/picamera.py` doesn't exist anymore I'm not sure there is anything to do about that here. `picamera` is imported from `imutils` so if there is a change to do it's in there.

**Comment by nischi** [comment]
true then lets close it
