### ISSUE TITLE
Not being matched

### ISSUE THREAD

**Issue by VedadTr** [nischi/MMM-Face-Reco-DNN#117]
Hi ! 

I installed openCV and your module successfully. I ran through all steps and at the moment, facial recognition does work, however im always detected as a stranger. I have set the folder inside dataset with 10 pictures ive took with the pi camera, i ran encode.py.

Been trying to fix this whole day without any luck. Any ideas what might be causing the matching problem ?

**Comment by VedadTr** [comment]
[somefile.txt](https://github.com/nischi/MMM-Face-Reco-DNN/files/9982756/somefile.txt)


start npm log

**Comment by VedadTr** [comment]
@nischi After some time debugging, it seems to be a problem inside the facerecognition.py.

Ive got an error in line 79:  AttributeError: 'int' object has no attribute 'isdigit'

**Comment by VedadTr** [comment]
![315228100_2947112495593682_2889184784605604984_n](https://user-images.githubusercontent.com/93086050/201165281-431d7d1e-088a-49a2-9baa-3b517c325781.png)

**Comment by nischi** [comment]
hi @VedadTr 
Do use a raspbi cam, correct? can you try to remove the setting `source` in your config?
