### ISSUE TITLE
Working module dependency versions (Nov 2022)

### ISSUE THREAD

**Issue by HW594** [nischi/MMM-Face-Reco-DNN#118]
With Raspberry Pi OS (Legacy), Debian Buster, Release date: September 22nd 2022
the following dependency versions are working:

| **Dependency** | **Versions** |
| ------------- | ------------- |
| OpenCV | 4.6.0.66|
| dlib | 19.24.0 |
| face_recognition | 1.3.0 |
| imutils |	0.5.4 |

**Comment by nischi** [comment]
Is updated, thank you
