### ISSUE TITLE
ExtentDataset only saving known pictures

### ISSUE THREAD

**Issue by SILLEN69** [nischi/MMM-Face-Reco-DNN#120]
Hey the problem is in the title, when i stand infront of the mirror it saves more pictures but when an unknown person steps infront of the camera it doesn't save new pictures do I need too create the unknown folder beside my profile folder or something for it too save?

**Comment by nischi** [comment]
hi. not sure to be honest, but i think it should create the folder if not exists. but you can try to create manually,

**Comment by SILLEN69** [comment]
Hey you can close this. I don't know what i did but the morning after it worked fine
