### ISSUE TITLE
error while trying to install MMM-Face-Reco-DNN

### ISSUE THREAD

**Issue by NightFalcon650** [nischi/MMM-Face-Reco-DNN#123]
I tried to install this module but i'm getting these errors.

![image](https://user-images.githubusercontent.com/7109209/210058308-6ffd3d29-39f3-4bbd-bb0d-47559774bfe7.png)

When i do a npm install --force i get the following errors:

![image](https://user-images.githubusercontent.com/7109209/210058456-b7b84a92-6cfd-4188-a6bd-fb9ed3386bfe.png)

After this i done the suggestion npm audit fix and still getting the errors:

![image](https://user-images.githubusercontent.com/7109209/210058597-62e54392-ef49-4dd6-a7a4-b3c04a268a42.png)

What do i have to do to fix this issue and get the module installed or is there a newer working version of face-recognition with MagicMirror?

**Comment by nischi** [comment]
Yes this could be because npm thinks they are version incompatibilties. But this is usualy fine. You can use `npm ci` instead of `npm install`. But it seems all fine after npm install --force. so dont worry.

**Comment by NightFalcon650** [comment]
> Yes this could be because npm thinks they are version incompatibilties. But this is usualy fine. You can use `npm ci` instead of `npm install`. But it seems all fine after npm install --force. so dont worry.

Thanks for your reply and best wishes for 2023.
I tried the NPM ci but it still gives errors. 
And when i add the classes to the config.js the mirror gives a error and starts the mirror with the default config.

![image](https://user-images.githubusercontent.com/7109209/210210256-8560334d-a72d-4da3-a0c6-2976e5242628.png)

Unfortunately it doesn't work and still looking for a working sollution..

**Comment by NightFalcon650** [comment]
> Wish you also the best for 2023. This error has nothing to do with the module itself. It seems you have a corupt configuration. Maybe a comma is missing or something like that. can you send me the config?

Thanks for the clear and quick reaction. 
Indeed i made the mistake of adding the classes and forgetting the comma. 
It's encoding my pics now, so hopefully when thats done it wil work :-D
