### ISSUE TITLE
face is recognized once and modules do not disappear over time

### ISSUE THREAD

**Issue by eurtnl** [nischi/MMM-Face-Reco-DNN#124]
Hello, I'm not sure if it is a mistake or if I have to adjust my expectations, but I run into the following problem:
I have set all modules to everyone or a specific user. When I start MagicMirror, a face is recognized after a few seconds
But when I walk away the modules remain visible, even after a few minutes of waiting. I expected that at some point the modules would be invisible again

My config:
Logoutdelay: 5000,
Check interval: 2000,

MagicMirror is installed on Raspbian Bullseye 64-bit and I use a USB camera

Any idea what I can adjust to get it working?

**Comment by nischi** [comment]
Hmm this should actualy work. not sure why it go away. can you send me the log and the full config?

**Comment by eurtnl** [comment]
[config.txt](https://github.com/nischi/MMM-Face-Reco-DNN/files/10328591/config.txt)
[localhost-1672566623801.log](https://github.com/nischi/MMM-Face-Reco-DNN/files/10328592/localhost-1672566623801.log)
[MagicMirror-error.log](https://github.com/nischi/MMM-Face-Reco-DNN/files/10328593/MagicMirror-error.log)
[MagicMirror-out.log](https://github.com/nischi/MMM-Face-Reco-DNN/files/10328594/MagicMirror-out.log)

**Comment by nischi** [comment]
Hmm i do not see any issue here. Is there a task which use maybe 100% CPU? Maybe the video stream of your camera is break down. Not sure whats wrong, seems all fine on Magic Mirror site.

**Comment by eurtnl** [comment]
Also, I have extendDataset: true and when I've recognized it takes a picture and puts it in dataset/my-name but sometimes it won't recognize me (I can see the light on the camera) and also there's no picture taken and put in dataset/unknown.
I will try another webcam see if that helps.

Btw Raspbian is installed on a SSD-drive and I use a 15w power adapter

**Comment by eurtnl** [comment]
Did a new install with Raspbian Buster and Pi camera. Now it's working.
Guess it has something to do with camera support in Bullseye
