### ISSUE TITLE
Increase resolution extendDataset

### ISSUE THREAD

**Issue by eurtnl** [nischi/MMM-Face-Reco-DNN#127]
Where can I change the resolution for the pictures taken when extendDataset = true?

**Comment by nischi** [comment]
at the moment the resolution cant be changed with a setting. but i think i can add this.

**Comment by eurtnl** [comment]
That would be a nice feature.
Until then, I found this line in /tools/picam.py
`class PiVideoStream:
	def __init__(self, resolution=(320, 240), framerate=32, rotation=0):`
Is that where I have to change the resolution?

**Comment by nischi** [comment]
Yes if you use the picam, this is the right file.

**Comment by eurtnl** [comment]
Ok, I changed the resolution to
`class PiVideoStream: def __init__(self, resolution=(1280, 960), framerate=32, rotation=0):`
But the pictures are still in 320,240

**Comment by nischi** [comment]
Hmm.. so do you have a picam? can you try to change it in https://github.com/nischi/MMM-Face-Reco-DNN/blob/master/tools/stream.py

**Comment by eurtnl** [comment]
I'm using a Picam Noir
Did change the setting in stream.py and picam.py but still resolution is 320,240
Even after a reboot

**Comment by nischi** [comment]
I created a new version with the settings to set the resolution. can you please check it out?

**Comment by eurtnl** [comment]
Yep it's working.
thank you!
