### ISSUE TITLE
Error when starting the mirror with MMM-Face-Reco-DNN installed

### ISSUE THREAD

**Issue by NightFalcon650** [nischi/MMM-Face-Reco-DNN#128]
Goodevening,

I've installed the Face-Reco module but when i start with NPM start i'm getting this error:
`
[21.01.2023 18:46.41.362] [LOG]   [MMM-Face-Reco-DNN] loading encodings + face detector...
[21.01.2023 18:46.41.450] [LOG]   [MMM-Face-Reco-DNN] starting video stream...
[21.01.2023 18:46.41.792] [ERROR] Whoops! There was an uncaught exception...
[21.01.2023 18:46.41.802] [ERROR] PythonShellError: OSError: libmmal.so: cannot open shared object file: No such file or directory
    at PythonShell.parseError (/home/magicmirror/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:295:21)
    at terminateIfNeeded (/home/magicmirror/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:190:32)
    at ChildProcess.<anonymous> (/home/magicmirror/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:182:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
`

What's going wrong and how can i get it to work?

**Comment by nischi** [comment]
hi @NightFalcon650 
It look like you did not installed the dependencies of my module. Did you run `npm ci` or `npm install` for my module?

**Comment by NightFalcon650** [comment]
> hi @NightFalcon650 It look like you did not installed the dependencies of my module. Did you run `npm ci` or `npm install` for my module?

yes i tried this a couple of times but that produces errors: 
`
magicmirror@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-standard@16.0.3
npm ERR! Found: eslint@8.30.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.30.0" from the root project
npm ERR!   peer eslint@">=5.16.0" from eslint-plugin-node@11.1.0
npm ERR!   node_modules/eslint-plugin-node
npm ERR!     dev eslint-plugin-node@"^11.1.0" from the root project
npm ERR!     peer eslint-plugin-node@"^11.1.0" from eslint-config-standard@16.0.3
npm ERR!     node_modules/eslint-config-standard
npm ERR!       dev eslint-config-standard@"^16.0.3" from the root project
npm ERR!   4 more (eslint-plugin-es, eslint-plugin-promise, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^16.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm ERR!   node_modules/eslint-config-standard
npm ERR!     dev eslint-config-standard@"^16.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/magicmirror/.npm/_logs/2023-01-22T20_37_06_170Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/magicmirror/.npm/_logs/2023-01-22T20_37_06_170Z-debug-0.log
`

I tried it with the --force but still no luck
I'm a little bit stuck and don't know what to do now??

**Comment by nischi** [comment]
hmm this is a little strange. did you tried `npm ci` instead of install?

**Comment by NightFalcon650** [comment]
> hmm this is a little strange. did you tried `npm ci` instead of install?

yes i did, tried it again and it produces these errros:
`
magicmirror@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ npm ci
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-standard@16.0.3
npm ERR! Found: eslint@8.30.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.30.0" from the root project
npm ERR!   peer eslint@">=5.16.0" from eslint-plugin-node@11.1.0
npm ERR!   node_modules/eslint-plugin-node
npm ERR!     dev eslint-plugin-node@"^11.1.0" from the root project
npm ERR!     peer eslint-plugin-node@"^11.1.0" from eslint-config-standard@16.0.3
npm ERR!     node_modules/eslint-config-standard
npm ERR!       dev eslint-config-standard@"^16.0.3" from the root project
npm ERR!   4 more (eslint-plugin-es, eslint-plugin-promise, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^16.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.12.1" from eslint-config-standard@16.0.3
npm ERR!   node_modules/eslint-config-standard
npm ERR!     dev eslint-config-standard@"^16.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/magicmirror/.npm/_logs/2023-01-23T05_57_46_725Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/magicmirror/.npm/_logs/2023-01-23T05_57_46_725Z-debug-0.log
`

**Comment by nischi** [comment]
can you give me the version of node and npm do you have?

```
npm --version
node --version
```

**Comment by NightFalcon650** [comment]
The versions are:
`
magicmirror@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ npm --version && node --version
9.2.0
v16.19.0
`

**Comment by nischi** [comment]
Maybe this is the problem, can you update to the latest node lts version. this should be 18.13. Not sure if this solve the problem, but could be.

**Comment by NightFalcon650** [comment]
> Maybe this is the problem, can you update to the latest node lts version. this should be `18.13`. Not sure if this solve the problem, but could be.

i've updated to 18 and tried it - no luck
After this i tried 19 and also - no luck
Uninstalled NodeJS and reinstalled version 18 again - no luck

Very strange :-S

**Comment by nischi** [comment]
This is very strange. i tried it, works fine without any issues. Can you try to manualy update the dev dependencies in package.json to the most actual ones?

```json
  "devDependencies": {
    "eslint": "^8.32.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-standard": "^5.0.0"
  }
````
you can remove the `eslint-config-standard`

**Comment by NightFalcon650** [comment]
> This is very strange. i tried it, works fine without any issues.
> 
> Can you try to avoid the dev dependencies, because you do not really ned them. `npm install --omit=dev`
> 
> Or can you try to manualy update the dev dependencies in package.json to the most actual ones?
> 
> ```json
>   "devDependencies": {
>     "eslint": "^8.32.0",
>     "eslint-plugin-import": "^2.27.5",
>     "eslint-plugin-node": "^11.1.0",
>     "eslint-plugin-promise": "^6.1.1",
>     "eslint-plugin-standard": "^5.0.0"
>   }
> ```
> 
> you can remove the `eslint-config-standard`

I tried both but without luck. Still giving errors. 

After this i removed MM completly, did a reinstall - no luck

At the end i've done a complete new install on a other SD-card and have the same issues. Searching further on the internet revealed that the MMAL libaries aren't supported on the newest PI4 OS. [https://askubuntu.com/questions/1434193/install-rpi-userland-on-arm64-pi-4-running-ubuntu-pi-22-04-server].
My cam works but not with the module. 
Still looking to get it working but don't know how. I'd like to help you in making, and testing it to get this great module to work.

**Comment by nischi** [comment]
but for my point of view this has nothing to do with the os. but we never know. 

so you removed the eslint dependencies completly from the package json and did a npm install and got the same error?
