### ISSUE TITLE
Enhancement - Create dataset for unrecognized people

### ISSUE THREAD

**Issue by ChrizZz90** [nischi/MMM-Face-Reco-DNN#13]
If the camera can't recognize a known person it should make screenshots in a selected or useful time period and save it in a new folder (timestamp? Like unknown_190831_1635). After that, the user can select the picture and create a new dataset.

**Comment by nischi** [comment]
Thats a nice idea, i like. Will try to implement it.

**Comment by nischi** [comment]
@ChrizZz90 i implemented it in a seperate branch. but at the moment it will save all frames where a face is recognized. also the known once (which are saved in there folder to retrain). but thats way to much i think. 
you said in a useful time period, any suggestion on that?

**Comment by nischi** [comment]
so i changed it to the first frame each "login"

**Comment by ChrizZz90** [comment]
can you maybe add that every user can select in his config if this module should save pictures of recognized people?
I have now lots of pictures with more than 1 person on the picture but only one was recognized. I don't know if it is a problem if I create now new embeddings. And there are too many pictures to check them first :)
