### ISSUE TITLE
OpenCV with PiCamera 2 and Bullseye OS needed changes

### ISSUE THREAD

**Issue by traceurSaimn** [nischi/MMM-Face-Reco-DNN#136]
Hi @nischi 

I istalled your fabulous module on my raspberry pi 4 with bullseye OS and PiCamera 2.
I am currently running it with the following lib versions:

- OpenCV: 4.7.0
- dlib: 19.22.1
- face_recognition: 1.2.3
- imutils: 0.5.4

I had some issues with running the VideoStream, as it was not able to work with libcamera. So I changed your facerecognition.py to make it work with the picamera2 package.

Firstly I imported the pycamera2 package:
```python
from picamera2 import Picamera2
```

So I fully removed the following lines, as they are not necessary anymore when only the PiCamera is attached:
```python
if args["source"].isdigit():
    src = int(args["source"])
else:
    src = args["source"]
```

Then I replaced the lines
```python
if args["usePiCamera"] >= 1:
	vs = VideoStream(usePiCamera=True, rotation=args["rotateCamera"], resolution=resolution).start()
else:
	vs = VideoStream(src=src, resolution=resolution).start()
```
with
```python
picam2 = Picamera2()
picam2.configure(picam2.create_preview_configuration(main={"format": 'XRGB8888', "size": (640, 480)}))
picam2.start()
```
Then, instead of getting the frame with `originalFrame = vs.read()` simply do `originalFrame = picam2.capture_array()`

Also I deactivated the `fps` counter and removed all related `fps` and `vs` related code.

Just wanted to tell you and I hope you keep maintaining this super project.

**Comment by nischi** [comment]
Hi @traceurSaimn 

Thank you for your input. i think i need to refactor my module to be more actual anyway. I will try to use only one lib that we can reduce the boilerplate. 

Thanks

**Comment by nischi** [comment]
It's out now :) Version 2.0
