### ISSUE TITLE
pipenv not installed

### ISSUE THREAD

**Issue by sdetweil** [nischi/MMM-Face-Reco-DNN#139]
```Successfully installed distlib-0.3.7 filelock-3.12.4 pipenv-2023.10.3 platformdirs-3.11.0 setuptools-68.2.2 virtualenv-20.24.5
pi@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ npm run postinstall

> mmm-face-reco-dnn@2.0.0 postinstall
> pipenv install --site-packages

sh: 1: pipenv: not found
```
pi@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ python --version
Python 3.9.2
pi@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ node -v
v20.8.0
pi@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ npm -v
10.1.0
pi@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN $ 

don't know anything about python

**Comment by nischi** [comment]
Hi @sdetweil 
You need to install pip and pipenv first.

https://pip.pypa.io/en/stable/installation/
https://pipenv.pypa.io/en/latest/installation/

**Comment by sdetweil** [comment]
you know  you could do that in the postinstall so I don't have to figure it out...
