### ISSUE TITLE
Direct Image Capture from Raspberry Pi

### ISSUE THREAD

**Issue by camillemarius** [nischi/MMM-Face-Reco-DNN#142]
I've created a straightforward script that provides an interactive method to capture images from a Raspberry Pi camera. Users can initiate photo capture by pressing the space key, and they can exit the application by using the 'esc' key. All captured images are automatically saved in a designated directory with sequential filenames. The question is whether it's worthwhile to add this script to the repository.

**Comment by nischi** [comment]
Hi @camillemarius 
Sure why not, i can add this as a new script in the package file to capture the dataset. You can maybe create a PR or send me the file?
Thank you
