### ISSUE TITLE
Small Typo in README.md

### ISSUE THREAD

**Issue by kschlichter** [nischi/MMM-Face-Reco-DNN#145]
[Module Usage](https://github.com/nischi/MMM-Face-Reco-DNN/blob/master/README.md#module-usage) has a small typo.  I believe haarcascae is meant to be haarcascade.  

    // xml to recognize with **haarcascae** 
      cascade: 'modules/MMM-Face-Reco-DNN/model/haarcascade_frontalface_default.xml',

Thanks again for all your work on this module.

**Comment by nischi** [comment]
hi @kschlichter 
you are right, i will fix this :) Thank you
