### ISSUE TITLE
Error syntax 

### ISSUE THREAD

**Issue by Kyliwoog** [nischi/MMM-Face-Reco-DNN#149]
hello, after following everything I have a problem. I spent several hours to install opencv.
`Linux MagicMirror 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Dec 29 00:37:55 2023 from 192.168.1.24
Elensar@MagicMirror:~ $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/Elensar/.pm2/pm2.log last 15 lines:
PM2        | 2023-12-29T00:30:57: PM2 log: Node.js version      : 20.8.0
PM2        | 2023-12-29T00:30:57: PM2 log: Current arch         : arm
PM2        | 2023-12-29T00:30:57: PM2 log: PM2 home             : /home/Elensar/.pm2
PM2        | 2023-12-29T00:30:57: PM2 log: PM2 PID file         : /home/Elensar/.pm2/pm2.pid
PM2        | 2023-12-29T00:30:57: PM2 log: RPC socket file      : /home/Elensar/.pm2/rpc.sock
PM2        | 2023-12-29T00:30:57: PM2 log: BUS socket file      : /home/Elensar/.pm2/pub.sock
PM2        | 2023-12-29T00:30:57: PM2 log: Application log path : /home/Elensar/.pm2/logs
PM2        | 2023-12-29T00:30:57: PM2 log: Worker Interval      : 30000
PM2        | 2023-12-29T00:30:57: PM2 log: Process dump file    : /home/Elensar/.pm2/dump.pm2
PM2        | 2023-12-29T00:30:57: PM2 log: Concurrent actions   : 2
PM2        | 2023-12-29T00:30:57: PM2 log: SIGTERM timeout      : 1600
PM2        | 2023-12-29T00:30:57: PM2 log: ===============================================================================
PM2        | 2023-12-29T00:30:57: PM2 log: [Watch] Start watching MagicMirror
PM2        | 2023-12-29T00:30:57: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2023-12-29T00:30:57: PM2 log: App [MagicMirror:0] online

/home/Elensar/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMir |     at node:internal/modules/cjs/loader:967:12
0|MagicMir |     at Function._load (node:electron/js2c/asar_bundle:2:13327)
0|MagicMir |     at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMir |     at require (node:internal/modules/cjs/helpers:110:18)
0|MagicMir |     at loadConfig (/home/Elensar/MagicMirror/js/app.js:117:14)
0|MagicMir |     at App.start (/home/Elensar/MagicMirror/js/app.js:247:18)
0|MagicMir |     at Object.<anonymous> (/home/Elensar/MagicMirror/js/electron.js:190:7)
0|MagicMir |     at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|MagicMir |     at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMir |     at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMir |     at node:internal/modules/cjs/loader:967:12
0|MagicMir | [1717:1229/003142.138977:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
0|MagicMir | [1794:1229/003145.201672:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization

/home/Elensar/.pm2/logs/MagicMirror-out.log last 15 lines:
0|MagicMir | [29.12.2023 00:31.39.246] [LOG]   Starting MagicMirror: v2.25.0
0|MagicMir | [29.12.2023 00:31.39.305] [LOG]   Loading config ...
0|MagicMir | [29.12.2023 00:31.39.316] [DEBUG] config template file not exists, no envsubst
0|MagicMir | [29.12.2023 00:31.39.362] [LOG]   Loading module helpers ...
0|MagicMir | [29.12.2023 00:31.39.448] [LOG]   Initializing new module helper ...
0|MagicMir | [29.12.2023 00:31.39.449] [LOG]   Module helper loaded: updatenotification
0|MagicMir | [29.12.2023 00:31.39.462] [LOG]   No helper found for module: helloworld.
0|MagicMir | [29.12.2023 00:31.39.463] [LOG]   All module helpers loaded.
0|MagicMir | [29.12.2023 00:31.39.502] [LOG]   Starting server on port 8080 ... 
0|MagicMir | [29.12.2023 00:31.41.110] [LOG]   Server started ...
0|MagicMir | [29.12.2023 00:31.41.112] [LOG]   Connecting socket for: updatenotification
0|MagicMir | [29.12.2023 00:31.41.123] [LOG]   Starting module helper: updatenotification
0|MagicMir | [29.12.2023 00:31.41.124] [LOG]   Sockets connected & modules started ...
0|MagicMir | [29.12.2023 00:31.41.388] [LOG]   Launching application.
0|MagicMir | [29.12.2023 00:31.49.268] [INFO]  Checking git for module: MagicMirror
`

**Comment by nischi** [comment]
Hi @Kyliwoog 
But this looks more like an error of another module

`org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files`
