### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Biteldamian** [nischi/MMM-Face-Reco-DNN#15]
Im having issues getting it working, sorry such a noob at this stuff

I installed everyrting
but i cant seem to make a good config file when i start the pm2 program it automaticly goes to the error where you need a config file

**Comment by nischi** [comment]
@Biteldamian Can you please provide your config that i can check whats wrong?

**Comment by Biteldamian** [comment]
i could not drop the json file so i made a txt
[config.txt](https://github.com/nischi/MMM-Face-Reco-DNN/files/3626864/config.txt)

**Comment by Biteldamian** [comment]
the dataset map is named 'damian'

**Comment by nischi** [comment]
you miss a comma before classes in module config from "compliments" and "clock".

```javascript
{
			module: "clock",
			position: "top_left"   <--- missing comma

			classes: 'damian',
},
```
