### ISSUE TITLE
ENABLE/DISABLE HELP

### ISSUE THREAD

**Issue by sidevil** [nischi/MMM-Face-Reco-DNN#16]
can i enable/disable the facial recognition modules using PIR sensors.
facial recognition is keeping camera busy all the time. so if i want to use camera for some other purpose its hard to do.

so is it possible ?

Thank you

**Comment by sidevil** [comment]
Or Else if i can see the live stream

cv2.imshow will this work ?? 

if yes then where and how should i put that. if i can see the stream on i frame then that will solve my one issue.. thank you :)

**Comment by nischi** [comment]
@sidevil 
What exactly you wanna do? Not sure if only one stream of camara are possible, i need to test.

**Comment by sidevil** [comment]
i have created one command to take photo using assistantmk2 module. and i am working on video call also. 

but as i hit the command to take photo the camera is busy in facial recognition. facial reco module keep camera always buys. so i want to use pir sensor to disable/enable facial recognition module. 

if that doesn't work then i want the live stream in iframe or like that so i will just go to that page and hit screenshot command using assistantmk2 so the taking photo problem will be solved. and for video calling i will attach other camera then. 


Thank you for your response. :)

**Comment by nischi** [comment]
okay i think thats not so easy to implement. But my module can also take a photo if he is recognize a face. Not sure that will solve your problem as well?

**Comment by sidevil** [comment]
nope probably not cause photo meant to be like selfie kind of photo. so we can upload that to facebook like social media. so there is only two option use second camera or else code whole module differently so that will work with PIR. right ? is there any easy third option :p
