### ISSUE TITLE
Module not showing up appropriately

### ISSUE THREAD

**Issue by unbeatable01** [nischi/MMM-Face-Reco-DNN#2]
I'm unable to get the module to show up correctly on the screen. I have attached an image of the display along with the config file, please help.
![IMG_20190703_145955222](https://user-images.githubusercontent.com/20066856/60584183-33c41380-9daa-11e9-9e2c-025264afc2b4.jpg)

`var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
			classes: "default everyone"
		},
		
		{
			module: "updatenotification",
			classes: "default everyone",
			position: "top_bar"
		},
		{
    module: 'MMM-Facial-Recognition-OCV3',
    position: 'top_left',
    classes: 'default everyone',
    config: {
        // Threshold for the confidence of a recognized face before it's considered a
        // positive match.  Confidence values below this threshold will be considered
        // a positive match because the lower the confidence value, or distance, the
        // more confident the algorithm is that the face was correctly detected.
        threshold: 80,
        // force the use of a usb webcam on raspberry pi (on other platforms this is always true automatically)
        useUSBCam: false,
        // Path to your training xml
        trainingFile: '/home/pi/MagicMirror/modules/MMM-Facial-Recognition-OCV3/training.xml',
        // recognition intervall in seconds (smaller number = faster but CPU intens!)
        interval: 2,
        // Logout delay after last recognition so that a user does not get instantly logged out if he turns away from the mirror for a few seconds
        logoutDelay: 15,
        // Array with usernames (copy and paste from training script)
        users: [],
        //Module set used for strangers and if no user is detected
        defaultClass: "default",
        //Set of modules which should be shown for every user
        everyoneClass: "everyone",
        // Boolean to toggle welcomeMessage
        welcomeMessage: true
    }
},
		{
			module: "clock",
			position: "top_left",
			classes: "default everyone"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			classes: "default everyone",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
    module: 'MMM-Face-Reco-DNN',
    classes: "default everyone",
    position: "top_right"
},
		{
			module: "compliments",
			position: "lower_third",
			classes: "default everyone"
		},
		{
			module: "currentweather",
			position: "top_right",
			classes: "default everyone",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			classes: "default everyone",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from https://openweathermap.org/city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			classes: "default everyone",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by ivanovd** [comment]
It seems that you have the MMM-Facial-Recognition-OCV3 and MMM-Face-Reco-DNN modules in the config file and for the latter you don't have any parameters set. These two module would fight with each other. You should remove the config for MMM-Facial-Recognition-OCV3 imho.

**Comment by nischi** [comment]
Thanks @ivanovd. And my module do not need any output, so you don‘t need to set any classes. I think you have an issue with the resources, not both module can use the pi cam at the same time i think (not tested yet).

Can you confirm that it works if you only use my module?

**Comment by unbeatable01** [comment]
I tried removing MMM-Facial-Recognition-OCV3 module from the config file, the module still doesn't show up properly on the screen.
Could you post some screenshots or a walkthrough please?

**Comment by nischi** [comment]
This module has no output, it works in the background, so its not necessary that you add a position. My Config looks like:

```js

    {
      module: 'MMM-Face-Reco-DNN',
			config: {
				// Logout 15 seconds after user was not detecte anymore, if they will be detected between this 15 Seconds, they delay will start again
				logoutDelay: 15000,
				// How many time the recognition starts, with a RasPi 3+ it would be good every 2 seconds
				checkInterval: 2000,
				// Module set used for strangers and if no user is detected
				defaultClass: 'default',
				// Set of modules which should be shown for every user
				everyoneClass: 'everyone',
				// XML to recognize with haarcascae
				cascade: 'modules/MMM-Face-Reco-DNN/tools/haarcascade_frontalface_default.xml',
				// Pre encoded pickle with the faces
				encodings: 'modules/MMM-Face-Reco-DNN/tools/encodings.pickle',
				// You wanna use pi camera or usb / builtin (1 = raspi camera, 0 = other camera)
				usePiCamera: 1,
				// Method of face detection (dnn = deep neural network, haar = haarcascade)
				method: 'dnn',
				// Which face detection model to use. "hog" is less accurate but faster on CPUs. "cnn" is a more accurate deep-learning model which is GPU/CUDA accelerated (if available).
				detectionMethod: 'hog',
				// How fast in ms should the modules hide and show (face effect)
				animationSpeed: 0
			}
		},
```

and for a module which shows all the time

```js
		{
			module: "clock",
			position: "top_left",
			classes: "default everyone"
		},
```

and for a module which shows for a specific user

```js

		{
			module: "calendar",
			classes: "john",
			header: "Feiertage",
			position: "top_left",
			config: {
				maximumNumberOfDays: 90,
				colored: true,
				coloredSymbolOnly: true,
				calendars: [
					{
						name: "feiertage",
						maximumEntries: 3,
						symbol: "circle",
						color: "#fe8308",
						url: "https://p64-calendars.icloud.com/holidays/ch_de-ch.ics"
					}
				]
			}
		},
```
