### ISSUE TITLE
welcome message

### ISSUE THREAD

**Issue by markusloe123** [nischi/MMM-Face-Reco-DNN#32]
Not really an issue, more of a question: is it possible to change the alert message itself?
Like, if I send an Alert via MMM-Remote-Control, it pops up in the center, and kinda hide the other modules. If someone could tell me how to approach, I´d be more than happy :D
Thanks in advance, great module btw!

**Comment by nischi** [comment]
@markusloe123 The message itself is fix in the module. But the send the message to the default alert module. So you can place it where you want. 
What you wanna change?

**Comment by markusloe123** [comment]
Like, telegram bot is using the same alert function i guess, and I would like to have the same position of the alert (in the center) and the same function (hiding the other modules) in the FaceReco module.
idk if this info is helpful enough :D

**Comment by nischi** [comment]
Can you send me the module link? so i can check what you exactly mean.

**Comment by markusloe123** [comment]
sure :
https://github.com/eouia/MMM-TelegramBot

**Comment by nischi** [comment]
Yes that's using the same alert module. So it should show the alert message on the same place.

**Comment by markusloe123** [comment]
you absolutely right, im an idiot sorry mate, i mean the remote-control module, not the telegram-bot 🤦🏻‍♂️

**Comment by nischi** [comment]
also this module use the same alert module. maybe you need to send me some pics if i do not understand.

Here you see the same code as on my module
```js
if (notification === "SHOW_ALERT") {
     this.sendNotification(notification, payload);
}
```

**Comment by markusloe123** [comment]
sure
<img width="1224" alt="face reco alert" src="https://user-images.githubusercontent.com/57556781/77289346-176e5b00-6cda-11ea-8ac6-248cfcb4d7d1.PNG">

<img width="1424" alt="remote alert" src="https://user-images.githubusercontent.com/57556781/77289361-1f2dff80-6cda-11ea-8f6b-81e53e387bf1.PNG">

**Comment by markusloe123** [comment]
sorry for the bad quality, but i hope you now know what i mean, the message below i sent with my phone, but i´d actually love to have your module welcomes me like that!

**Comment by nischi** [comment]
I do not understand 100% how the remote control module send the alert notification. But for me it looks like they send it the same way then i do. But maybe you can style the alert message like this and do it to the same position. I do not think it make sense that i send something to the remote control module. i do not want this dependency.
