### ISSUE TITLE
[ERROR]  (node:4460) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by anoobgaymer** [nischi/MMM-Face-Reco-DNN#33]
I get this error when I have already installed everything using "sudo pip3 install".

> [ERROR]  (node:4460) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [20:23:58.260] [LOG]    Refreshed access token because it has expired. Expired at: 20:23:57 now is: 20:23:58
> [20:24:04.015] [LOG]    [MMM-Face-Reco-DNN] loading encodings + face detector...
> [20:24:04.197] [LOG]    Whoops! There was an uncaught exception...
> [20:24:04.197] [ERROR]  { Error: FileNotFoundError: [Errno 2] No such file or directory: 'modules/MMM-Face-Reco-DNN/tools/encodings.pickle'
>     at PythonShell.parseError (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:246:21)
>     at terminateIfNeeded (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:129:32)
>     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:121:13)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
>     ----- Python Traceback -----
>     File "modules/MMM-Face-Reco-DNN/tools/facerecognition.py", line 66, in <module>
>       data = pickle.loads(open(args["encodings"], "rb").read())
>   traceback:
>    'Traceback (most recent call last):\n  File "modules/MMM-Face-Reco-DNN/tools/facerecognition.py", line 66, in <module>\n    data = pickle.loads(open(args["encodings"], "rb").read())\nFileNotFoundError: [Errno 2] No such file or directory: \'modules/MMM-Face-Reco-DNN/tools/encodings.pickle\'\n',
>   executable: 'python3',
>   options: null,
>   script: 'modules/MMM-Face-Reco-DNN/tools/facerecognition.py',
>   args:
>    [ '--cascade=modules/MMM-Face-Reco-DNN/tools/haarcascade_frontalface_default.xml',
>      '--encodings=modules/MMM-Face-Reco-DNN/tools/encodings.pickle',
>      '--usePiCamera=1',
>      '--method=dnn',
>      '--detectionMethod=hog',
>      '--interval=2000',
>      '--output=0',
>      '--extendDataset=False',
>      '--dataset=modules/MMM-Face-Reco-DNN/dataset/' ],
>   exitCode: 1 } 
>

**Comment by anoobgaymer** [comment]
I am new to everything and I have just been following the steps. I skipped the Docker container and I think it's what's causing the errors that I have. I'm not sure what to do for this part. 

![docker](https://user-images.githubusercontent.com/62299947/77701771-ef6b4a00-6fae-11ea-8ac2-f84b45cfb4a4.png)

**Comment by nischi** [comment]
you do not need to do the encoding.pickle in a docker container. you can do that also on your machine. do you have create this encoding.pickle? seems not
