### ISSUE TITLE
Set rotation of PiCamera

### ISSUE THREAD

**Issue by AlphaMycelium** [nischi/MMM-Face-Reco-DNN#34]
It'd be nice to provide an option to [set the rotation](https://picamera.readthedocs.io/en/latest/api_camera.html#picamera.PiCamera.rotation) of the camera when using the Raspberry Pi camera module. This is useful if the camera is mounted the wrong way around for the default orientation.

I have managed to do this temporarily by modifying `picam.py` and adding the line `self.camera.rotation = 270`, but a config option would be better.

**Comment by nischi** [comment]
That sounds like a good thing.

**Comment by DrSoops** [comment]
I am getting the following error
`vs = VideoStream(usePiCamera=True, rotation=args["rotateCamera"]).start()\nTypeError: __init__() got an unexpected keyword argument \'rotation\'`
I'm not going to pretend I know python that well (or even care to learn python) but if i would hinder a guess the import statement in tools/facerecognition.py should be changed from 
```
from imutils.video import FPS, VideoStream
```
to
```
from imutils.video import FPS
from stream import VideoStream
```

**Comment by nischi** [comment]
@njoerd114 any idea?
