### ISSUE TITLE
Had pi one week and Face-Reco working great but

### ISSUE THREAD

**Issue by mm1964** [nischi/MMM-Face-Reco-DNN#46]
Please excuse me, I am not by any stretch of the imagination a coder in way, but I created a MM and installed your Module on it and it is working great on my pi3 B+.

Can I ask, how I would use your module to play a .WAV or .MP3 file when user is detected, I am also looking to add a Face Recon door lock. Any guidance would be appreciated 

Great module and easy to follow guide, even for me.  One week with Magic Mirror and a Pi.

**Comment by nischi** [comment]
Thanks a lot for the compliment. Phu good question. My Module send an event to the MagicMirror which can catch by another module. So i can imagine you can create an own module which catch this event and play a mp3 file.

**Comment by mm1964** [comment]
Nischi
Thank you and again, a great module. Even for a someone with zero knowledge about coding. I will research how to catch the event and play the mp3 or activate a GPIO pin for a lock
