### ISSUE TITLE
Alert notification

### ISSUE THREAD

**Issue by sdmydbr** [nischi/MMM-Face-Reco-DNN#50]
Well this is more of a feature request than an issue, the module itself is working well but it would be more complete if this particular feature is added. So I set the interval to 2 seconds so each time I’m infront  of the mirror, the mirror keeps on updating and sending the alert notification and since I have google tts enabled , it keeps on announcing; it would be more perfect if the face-reco module doesn’t send an alert notification if the same user is detected the second time in and only send alert notification the next time a new user is detected.

**Comment by nischi** [comment]
This make absolulty sense to me. So maybe somebody has time to implement, or i do it after holiday.
