### ISSUE TITLE
Need help coding logins/logouts

### ISSUE THREAD

**Issue by majurgens** [nischi/MMM-Face-Reco-DNN#58]
Hi

I'm trying to fix the a problem in the following scenario:

1. multiple concurrent logins disabled
2. user 1 moves in front of camera
3. login occurs properly
4. user 2 moves in front of camera
5. login attempted but rejected
6. user 1 moves away from camera
7. user 1 logout occurs
8. EXPECTING: user 2 login occurs, but it never does, until the next step
9. user 2 moves away from camera
10. user2 moves back in front of camera
11. user 2 login occurs properly 

Whilst I am expecting the user 2 login to occur (STEP 8) it does not because something still thinks that user 2 is logged in until they actually move away from the camera. 

Something else is holding user 2 as logged in while they stay in front of the camera.

The logins/logouts appear to be driven by something else, probably the python code. I don't quite understand how there are working and calling the `socketNotificationReceived` function. 

So, I am not currently sure how I can resolve this problem. I might need help with the python code, if that is what is hold the user as logged in until they move away

Thanks

**Comment by nischi** [comment]
Phu good question. Never had this issue. Need to investigate on this.

**Comment by majurgens** [comment]
I have put more code in my local version to work around this and I soon will start supporting multi-concurrent users so this may help. Are you able to give me some info on how the python code interacts?
