### ISSUE TITLE
Default Modules Not Showing Up

### ISSUE THREAD

**Issue by dhriti-krishna** [nischi/MMM-Face-Reco-DNN#60]
Hi, 

This module works perfectly. And when it recognizes me, it says hi to me. But the default modules are not showing up. All I can see is a blank screen.
How do I fix this?

**Comment by nischi** [comment]
What did you set as classes for thr default modules?

**Comment by dhriti-krishna** [comment]
Hi, I didn't actually put the classes as I didn't know where to put them. Can you please help me? 

This is my config.js modules part - 

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "My Calendar",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: ""				
                                         }
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "",
				locationID: "", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: ""
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "",
				locationID: "", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: ""
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "",
						url: ""
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		{
		  module: "MMM-GoogleAssistant",
		  position: "fullscreen_above",
		  config: {
		    debug: false,
		    assistantConfig: {
		      lang: "en-US",
		      projectId: "test1-8e232", // Required to use gaction.
		      modelId: "", // (OPTIONAL for gaction)
		      instanceId: "", // (OPTIONAL for gaction)
		      latitude: ,
		      longitude: ,
		    },
		    responseConfig: {
		      useScreenOutput: true,
		      screenOutputCSS: "screen_output.css",
		      screenOutputTimer: 5000,
		      screenRotate: false,
		      activateDelay: 250,
		      useAudioOutput: true,
		      useChime: true,
		      newChime: false,
		      useNative: true,
		      playProgram: "mpg321"
		    },
		    micConfig: { // put there configuration generated by auto-installer
		      recorder: "arecord",
		      device: "plughw:0",
		    },
		    customActionConfig: {
		      autoMakeAction: false,
		      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
		      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
		    },
		    snowboy: {
		      audioGain: 2.0,
		      Frontend: true,
		      Model: "jarvis",
		      Sensitivity: null
		    },
		    A2DServer: {
		      useA2D: true,
		      stopCommand: "stop"
		    },
		    recipes: [ "with-MMM-TelegramBot.js"]
		  }
		},
		{
		  module: "MMM-Assistant2Display",
		  position: "top_left",
		  config: {
		    debug:false,
		    useYoutube: true,
		    links: {
		      useLinks: false,
		      displayDelay: 60 * 1000,
		      scrollStep: 25,
		      scrollInterval: 1000,
		      scrollStart: 5000,
		      scrollActivate: false,
		      verbose: false
		    },
		    photos: {
		      usePhotos: true,
		      displayDelay: 10 * 1000
		    },
		    volume: {
		      useVolume: true,
		      volumePreset: "ALSA",
		      myScript: null
		    },
		    briefToday: {
		      useBriefToday: false,
		      welcome: "Brief Today"
		    },
		    screen: {
		      useScreen: false,
		      delay: 5 * 60 * 1000,
		      turnOffDisplay: true,
		      ecoMode: true,
		      displayCounter: true,
		      displayBar: false,
		      displayStyle: "Text",
		      text: "Auto Turn Off Screen:",
		      detectorSleeping: false,
		      governorSleeping: false,
		      rpi4: false
		    },
		    pir: {
		      usePir: false,
		      gpio: 21,
		      reverseValue: false
		    },
		    governor: {
		      useGovernor: false,
		      sleeping: "powersave",
		      working: "ondemand"
		    },
		    internet: {
		      useInternet: false,
		      displayPing: false,
		      delay: 2 * 60 * 1000,
		      scan: "google.fr",
		      command: "pm2 restart 0",
		      showAlert: true
		    },
		    TelegramBot: {
		      useTelecastSound: false,
		      TelecastSound: "TelegramBot.ogg"
		    },
		    cast: {
		      useCast: true,
		      castName: "",
		      port: 
		    },
		    spotify: {
		      useSpotify: false,
		      useIntegred: false,
		      useLibrespot: false,
		      connectTo: "Librespot",
		      playDelay: 3000,
		      minVolume: 10,
		      maxVolume: 100,
		      updateInterval: 1000,
		      idleInterval: 10000,
		      username: "",
		      password: "",
		      CLIENT_ID: "",
		      CLIENT_SECRET: "",
		      deviceDisplay: "Listening on",
		      usePause: true
		    }
		  }
		},
		{
		    module: 'MMM-AlarmClock',
		    position: 'top_right',
		    config: {
			alarms: [
			    {time: "7:30 PM", days: [1], title: "Test1", message: "TT", sound: "alarm.mp3"},
				],
			}
		},
		{
		      module: 'MMM-Face-Reco-DNN',
		      config: {
			// Logout 15 seconds after user was not detected any more
			// If they are detected within this period, the delay will start again
			logoutDelay: 15000,
			// How often the recognition starts in milliseconds
			// With a Raspberry Pi 3+ it works well every 2 seconds
			checkInterval: 2000,
			// Module set used for when there is no face detected ie no one is in front of the camera
			noFaceClass: 'noface',
			// Module set used for when there is an unknown/unrecognised face detected 
			unknownClass: 'unknown',
			// Module set used for when there is a known/recognised face detected 
			knownClass: 'known',
			// Module set used for strangers and if no user is detected
			defaultClass: 'default',
			// Set of modules which should be shown for any user ie when there is any face detected
			everyoneClass: 'everyone',
			// Set of modules that are always shown - show if there is a face or no face detected
			alwaysClass: 'always',
			// XML to recognize with haarcascade
			cascade: 'modules/MMM-Face-Reco-DNN/tools/haarcascade_frontalface_default.xml',
			// Pre-encoded pickle with the faces
			encodings: 'modules/MMM-Face-Reco-DNN/tools/encodings.pickle',
			// Use Raspberry Pi camera or another type
			// 1 = RasPi camera, 0 = other camera
			usePiCamera: 1,
			// If using another type of camera, you can choose
			// i.e. 0 = /dev/video0 or 'http://link.to/live'
			source: 0,
			// Rotate camera
			rotateCamera: 0,
			// Method of facial recognition
			// dnn = deep neural network, haar = haarcascade
			method: 'dnn',
			// Which face detection model to use
			// "hog" is less accurate but faster on CPUs
			// "cnn" is a more accurate deep-learning model which is GPU/CUDA accelerated
			detectionMethod: 'hog',
			// How long in milliseconds modules take to hide and show
			animationSpeed: 0,
			// Path to Python to run the face recognition
			// null or '' means default path
			pythonPath: null,
			// Should a welcome message be shown using the MagicMirror alerts module?
			welcomeMessage: true,
			// Capture new pictures of recognized people, if unknown we save it in folder "unknown"
			// So you can extend your dataset and retrain it afterwards for better recognitions
			extendDataset: false,
			// If extendDataset is true, you need to set the full path of the dataset
			dataset: 'modules/MMM-Face-Reco-DNN/dataset/',
			// How much distance between faces to consider it a match. Lower is more strict.
			tolerance: 0.6,
			// allow multiple concurrent user logins, 0=no, 1=yes
			multiUser: 0,
		      }
		  },
	  ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

_________________________________________________________

Can you please tell me where to add the classes(I'm a noob)?

**Comment by dhriti-krishna** [comment]
Hi.

I actually forgot to set the classes!

Anyways, I set the classes and now, it works! Thanks again, @nischi.

I'm going to close this issue now.
