### ISSUE TITLE
Can you display the video on the mirror?

### ISSUE THREAD

**Issue by DeepKeys** [nischi/MMM-Face-Reco-DNN#68]
In the python file, images are shown using cv2.imshow(). Is there a way to show these on the mirror? This makes it visual and shows people what's going on under the hood, would be a cool feature!

Cheers

**Comment by nischi** [comment]
Theoreticaly is this possible. Not sure how much power this will need. But would be nice if somebody else could do this. I have a little less time now.

**Comment by RaspiManu** [comment]
This would really be a nice feature for showing interested friends how the detection works 👍

**Comment by nischi** [comment]
Is added in version 2.0
