### ISSUE TITLE
PiCamera vs others cameras

### ISSUE THREAD

**Issue by goldyfruit** [nischi/MMM-Face-Reco-DNN#69]
Hi @nischi,

In `facerecognition.py` script I see a `--usePiCamera` option, does this option increase performances compare to not using it?

I'm using the Pi Camera V2 module connected via the SPI connector but I can't use the `picamera` Python library because this library relies on the `libmmal` library which can't be used yet with the 64-bit versions.

Thanks for the great work. :+1:

**Comment by nischi** [comment]
Hi @goldyfruit 
Sorry for the late reply. No this is only that the Script use the SPI connector camera.
