### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Aquamannno** [nischi/MMM-Face-Reco-DNN#71]
need expertise help now. have installed docker and as you can see it has followed this installation with (https://github.com/nischi/MMM-Face-Reco-DNN but with 4.5 and so on with this (dlib, face_recognition, imutils, pip3 install numpy) etc.
have used this (python3 encode.py -i ../dataset/ -e encodings.pickle -d hog) and is ok but when it comes to this (cd tools;
make # generate an encodings.pickle with hog, or alternatively
make encoding = cnn # overide the default to use cnn encoding)
for me this error message here (pi @ raspberrypi: ~ / MagicMirror / modules / MMM-Face-Reco-DNN / tools $ make
docker build --build-arg UID = 1000 --build-arg GID = 1000 -t mmm-face-reco-dnn-dataset-runner.
ERRO [0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host ?: dial unix /var/run/docker.sock: connect: permission denied
error during connect: Post http: //%2Fvar%2Frun%2Fdocker.sock/v1.40/build? buildargs =% 7B% 22GID% 22% 3A% 221000% 22% 2C% 22UID% 22% 3A% 221000% 22 % 7D & cachefrom =% 5B% 5D & cgroupparent = & cpuperiod = 0 & cpuquota = 0 & cpusetcpus = & cpusetmems = & cpushares = 0 & dockerfile = Dockerfile & labels =% 7B% 7D & memory = 0 & memswap = 0 & networkmode = & 28 = & ulimits = null & version = 1: context canceled
ERRO [0000] Can't add file /home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/tools/encodings.pickle to tar: io: read / write on closed pipe
make: *** [Makefile: 6: image] Error 1
Then I feel like seeing something wrong with the docker so I tried this again
(sudo docker run --rm hello-world) and got this back
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm32v7)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
But have a question regarding this (pip3 install face_recognition)
for there for I first time installing path error in orange text.
With regards
Roy Bråthe Norway (used google transtlate)

**Comment by nischi** [comment]
@anderm3 Do you have maybe any idea?

**Comment by anderm3** [comment]
I think you have a permissions issue. You need to add the pi user to the docker group (and relogin in order to pick up the change.)

In your errors I see:
```
pi @ raspberrypi: ~ / MagicMirror / modules / MMM-Face-Reco-DNN / tools $ make
docker build --build-arg UID = 1000 --build-arg GID = 1000 -t mmm-face-reco-dnn-dataset-runner.
ERRO [0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host ?: dial unix /var/run/docker.sock: connect: permission denied
```

and in your troubleshooting:
```
(sudo docker run --rm hello-world) and got this back
Hello from Docker!
```

It looks like things are working as root but not as the pi user.
