### ISSUE TITLE
Error: ImportError: libtesseract.so.4

### ISSUE THREAD

**Issue by legendarynoob32** [nischi/MMM-Face-Reco-DNN#72]
Hey guys, i'm not a coder or anything of the sort, just trying to build a smart mirror and gift it to my mother before christmas, sorry if this is a stupid question and an easy fix. Any help would be appreciated!

When I run the python script I get this nasty error. 

`pi@raspberrypi:~/MagicMirror/modules/MMM-Face-Reco-DNN/tools $ python3 encode.py
Traceback (most recent call last):
  File "encode.py", line 5, in <module>
    from imutils import paths
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/convenience.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 89, in <module>
    bootstrap()
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 79, in bootstrap
    import cv2
ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
`

**Comment by nischi** [comment]
Did you install the OpenCV? And how you did it?

You can check if its installed if you try following commands in terminal:

```sh
python3
import cv2
```

And if this is working you can check the version with this additional command

```sh
cv2.__version__
```

**Comment by stefan-sherwood** [comment]
`pip3 install opencv-python==4.4.0.46`

**Comment by ankesh27** [comment]
@legendarynoob32 , any solution here? Even I am facing the same error and I have installed opencv
@nischi 
`python3
import cv2
cv2.__version__`

This is working and giving me the opencv version number.

**Comment by stefan-sherwood** [comment]
> This is working and giving me the opencv version number.

Ok, what is the version?
