### ISSUE TITLE
Not an Issue, just a compatibility report

### ISSUE THREAD

**Issue by RaspiManu** [nischi/MMM-Face-Reco-DNN#76]
Hey @nischi ,

Thank you so much for your great work. This module works like a charm 👍 
I just wanted to report, that I used the following versions with success:

OpenCV               4.5.0
dlib                      19.21.0
face_recognition   1.3.0
imutils                  0.5.3

Best Wishes,
Manuel

**Comment by nischi** [comment]
Awesome, thanks. Will add this to the readme
