### ISSUE TITLE
Module not loaded

### ISSUE THREAD

**Issue by evgenblum** [nischi/MMM-Face-Reco-DNN#78]
Hello, I install everything but while loading the module I get the next errors-
![MM_errors](https://user-images.githubusercontent.com/61081243/101895614-6d5c9900-3bb0-11eb-9382-503b98e8f11f.png)

Can you help me please?

**Comment by shivansh7299** [comment]
I got the same error please help...

**Comment by nischi** [comment]
Which Raspberry do you have and which camera do you have? Is the Camera working?

**Comment by evgenblum** [comment]
I use buster on PI 3 B+. Camera PI works fine and module MMM-MotionDetector based on this camera works.

**Comment by evgenblum** [comment]
When I wrote the previous post I thought maybe MMM-MotionDetector catch the camera and prevent loading your module. I remarked configuration  MMM-MotionDetector and your module now loading. But I see a black screen and magic mirror
![Screenshot_1](https://user-images.githubusercontent.com/61081243/101982229-0657e680-3c7b-11eb-8cb5-6fe5868b8c6a.png)
 can't load.

**Comment by evgenblum** [comment]
I got it, I forgot to set classes: 'always' for modules. Now I can see magic mirror screen. The last problem,- it can't detect my face. There is any clue to investigate why it can't detect my face?

**Comment by nischi** [comment]
did you create the pickle encoding eith a dataset?

**Comment by evgenblum** [comment]
yes. I have encodings.pickle
![Screenshot_2](https://user-images.githubusercontent.com/61081243/101983280-bd0b9500-3c82-11eb-8d23-4cdbec04bbf5.png)

**Comment by evgenblum** [comment]
May be I should rotate camera? What value should I set to rotateCamera for rotating 180 degrees?

**Comment by nischi** [comment]
phu not sure, try 😊

**Comment by evgenblum** [comment]
Yes, it's a rotated camera problem. Unfortunately, I can't find the right value for rotateCamera. I tried 0,1,2,3,180 - nothing helped. Only the physical rotation of the camera helps me to solve this problem. In my case, it's not the best solution.

**Comment by nischi** [comment]
not sure about the values. dis not this feature.

**Comment by evgenblum** [comment]
Maybe you know, there is a way to personalize global greetings from the compliments module? Or personalize your welcome message to show different texts for a specific person.

**Comment by nischi** [comment]
nope sorry

**Comment by stefan-sherwood** [comment]
You have to use the same rotation for the images you build the model with as when detecting. If your model doesn't include pictures in similar lighting it can also fail for that reason too.
