### ISSUE TITLE
How to hide or show modules for specific users in runtime?

### ISSUE THREAD

**Issue by dipato** [nischi/MMM-Face-Reco-DNN#80]
Dear all,

The face recognition part is working very well. My problem is when I want that a specific module was shown for a specific user. When I use "classes: 'always'", it shows well the modules, but when I use for example "classes: 'Diana'" in a module, this is not shown in the mirror. Also, if I use "classes: 'known'", the module is not shown. Can someome help me?

Thank you.

**Comment by nischi** [comment]
Hi @dipato 

This should actually work, i have the same. For the module which i wanna only show to myself i have the `classes: "thierry"`. You need to be carefull, it is case sensitive, is this maybe an issue?

**Comment by dipato** [comment]
Thank you dear Thierry, now it is working perfectly. Nice work!
