### ISSUE TITLE
Individual config for a class

### ISSUE THREAD

**Issue by Bl4CkGuuN** [nischi/MMM-Face-Reco-DNN#82]
Is it possible to have a individual config for a class?

ex. for every class other news from the newsfeed

**Person 1** wants to see news from: **Golem** and **Reddit**
**Person 2** wants to see news from: **BILD** and **Tagesschau**

**Comment by nischi** [comment]
Hi
This should be possible if you add the news module twice. One for Person 1 and one for Person 2?

**Comment by Bl4CkGuuN** [comment]
Yeah it is, but the config file is getting a bit chaotic then, if I have like 5 different persons.

Is the module then loading in the background or just hidden?

**Comment by nischi** [comment]
It is just hidding

**Comment by Bl4CkGuuN** [comment]
Okay, is it possible to implement different configs for the users?
Would be a cool feature.

**Comment by nischi** [comment]
i think this will go too deep in MagicMirror

**Comment by Bl4CkGuuN** [comment]
Okay, then I have to use multiple modules :)
