### ISSUE TITLE
OAK-1 and this module

### ISSUE THREAD

**Issue by goldyfruit** [nischi/MMM-Face-Reco-DNN#86]
Hey @nischi 

Just a random question, do you think that OpenCV AI Kit could work with your module?
Here is the link to the "camera": https://store.opencv.ai/products/oak-1

It seems to work with `dephtai` and there is an integration with OpenCV _(of course)_ but I'm wondering how the module could connect to this device?

**Comment by nischi** [comment]
Theoreticaly it should work. But i can't give you a guarantee
