### ISSUE TITLE
Seems to not work nicely with MMM-PIR-Sensor

### ISSUE THREAD

**Issue by gregersdk** [nischi/MMM-Face-Reco-DNN#94]
Using this on an older monitor (no CEC), I wanted to use a PIR sensor to turn the monitor on and off by shutting off and turning off HDMI on the RPi.

Worked perfectly until I installed this module. Set the PIR config to classes: 'always', but the PIR seems to stop working entirely. When the time is up, HDMI shuts off and I cannot turn it on again, having to unplug the Pi.

Seems to maybe work (register motion) when Face-Reco changes states (e.g. from unknown to known face), but not sure. Only worked once and when HDMI shut off, still no luck turning the monitor on again.

**Comment by nischi** [comment]
Hmm not sure why my module is causing this problem. do you have something in the logs?
